## Generate expected results for back tests

This notebook generates results for backtests. These include

* Backtests for run of simulation with default parameters (`test_backtest.py`).
* Backtests for runs of simulation where you are determining an appropriate number of replications (`test_backtest_replications.py`).

They save the relevant results dataframe as `.csv`, and use these to verify that the model produces consistent results.

The run time is provided at the end of this notebook.

## Set-up

Load required packages.

In [1]:
# pylint: disable=missing-module-docstring
# To ensure any updates to `simulation/` are fetched without needing to restart
# the notebook environment, reload `simulation/` before execution of each cell
%load_ext autoreload
%autoreload 1
%aimport simulation

In [2]:
# pylint: disable=wrong-import-position
# Import required packages
import os
import time
from IPython.display import display

import pandas as pd

from simulation import Param, Runner, run_scenarios

Start timer.

In [3]:
# Start timer
start_time = time.time()

Define path to expected results.

In [4]:
# Define path to folder for expected results for tests
TESTS = "../tests/exp_results/"

## Run of simulation with default parameters

In [5]:
# Define model parameters
param = Param(
    patient_inter=4,
    mean_n_consult_time = 10,
    number_of_nurses = 4,
    warm_up_period = 500,
    data_collection_period = 1500,
    number_of_runs=5,
    scenario_name = 0,
    cores = 1
)

# Run the replications
experiment = Runner(param)
experiment.run_reps()

In [6]:
# Patient-level results
display(experiment.patient_results_df)
experiment.patient_results_df.to_csv(
    os.path.join(TESTS, "patient.csv"), index=False)

,patient_id,arrival_time,q_time_nurse,time_with_nurse,end_time,run,q_time_unseen_nurse,time_in_system
0,1,504.513444,0.0,1.664896,506.178340,0,NaN,1.664896
1,2,507.230909,0.0,29.462508,536.693417,0,NaN,29.462508
2,3,508.394374,0.0,7.345594,515.739968,0,NaN,7.345594
3,4,512.975372,0.0,7.986073,520.961445,0,NaN,7.986073
4,5,521.933116,0.0,7.127312,529.060428,0,NaN,7.127312
...,...,...,...,...,...,...,...,...
1885,365,1978.104484,0.0,1.712059,1979.816543,4,NaN,1.712059
1886,366,1980.171724,0.0,11.023619,1991.195343,4,NaN,11.023619
1887,367,1986.506388,0.0,8.212316,1994.718704,4,NaN,8.212316
1888,368,1988.648731,0.0,24.898160,NaN,4,NaN,NaN
1889,369,1993.658168,0.0,3.353385,1997.011553,4,NaN,3.353385

In [7]:
# Run results
display(experiment.run_results_df)
experiment.run_results_df.to_csv(
    os.path.join(TESTS, "run.csv"), index=False)

,run_number,scenario,arrivals,mean_q_time_nurse,mean_time_with_nurse,mean_nurse_utilisation,mean_nurse_utilisation_tw,mean_nurse_q_length,count_nurse_unseen,mean_q_time_nurse_unseen,mean_time_in_system,mean_n_in_system
0,0,0,403,2.043788,9.577436,0.642332,0.642332,0.549098,0,NaN,11.612615,3.118427
1,1,0,382,1.255117,10.208371,0.646797,0.646797,0.319636,0,NaN,11.318952,2.906826
2,2,0,369,3.392586,10.731510,0.668010,0.668010,0.835793,0,NaN,13.927225,3.507834
3,3,0,367,2.227175,10.523889,0.639573,0.639573,0.544915,0,NaN,12.631501,3.103206
4,4,0,369,1.653496,9.809751,0.601042,0.601042,0.406760,0,NaN,11.426739,2.810927

In [8]:
# Overall results
display(experiment.overall_results_df)
experiment.overall_results_df.to_csv(
    os.path.join(TESTS, "overall.csv"), index=True)

,arrivals,mean_q_time_nurse,mean_time_with_nurse,mean_nurse_utilisation,mean_nurse_utilisation_tw,mean_nurse_q_length,count_nurse_unseen,mean_q_time_nurse_unseen,mean_time_in_system,mean_n_in_system
mean,378.000000,2.114432,10.170191,0.639551,0.639551,0.531240,0.0,NaN,12.183406,3.089444
std_dev,15.198684,0.806577,0.480342,0.024255,0.024255,0.195914,0.0,NaN,1.105365,0.267862
lower_95_ci,359.128341,1.112935,9.573768,0.609435,0.609435,0.287981,0.0,NaN,10.810915,2.756849
upper_95_ci,396.871659,3.115930,10.766615,0.669667,0.669667,0.774500,0.0,NaN,13.555898,3.422039

## Scenario analysis

In [9]:
# Run scenarios
param = Param(
    patient_inter=4,
    mean_n_consult_time=10,
    number_of_nurses=5,
    warm_up_period=2000,
    data_collection_period=6000,
    number_of_runs=3,
    cores=1
)
scenario_results = run_scenarios(
    scenarios={"patient_inter": [3, 4],
               "number_of_nurses": [6, 7]},
    param_factory=lambda: param
)

# Preview
display(scenario_results.head())

# Save to csv
scenario_results.to_csv(os.path.join(TESTS, "scenario.csv"), index=True)

There are 4 scenarios. Running:
{'patient_inter': 3, 'number_of_nurses': 6}
Scenario parameters: {'_initialising': False, 'patient_inter': 3, 'mean_n_consult_time': 10, 'number_of_nurses': 6, 'warm_up_period': 2000, 'data_collection_period': 6000, 'number_of_runs': 3, 'scenario_name': 0, 'cores': 1, 'seed_offset': 0, 'logger': <simulation.simlogger.SimLogger object at 0x7e5fd37d7a10>}
{'patient_inter': 3, 'number_of_nurses': 7}
Scenario parameters: {'_initialising': False, 'patient_inter': 3, 'mean_n_consult_time': 10, 'number_of_nurses': 7, 'warm_up_period': 2000, 'data_collection_period': 6000, 'number_of_runs': 3, 'scenario_name': 1, 'cores': 1, 'seed_offset': 0, 'logger': <simulation.simlogger.SimLogger object at 0x7e5fd37d7a10>}
{'patient_inter': 4, 'number_of_nurses': 6}
Scenario parameters: {'_initialising': False, 'patient_inter': 4, 'mean_n_consult_time': 10, 'number_of_nurses': 6, 'warm_up_period': 2000, 'data_collection_period': 6000, 'number_of_runs': 3, 'scenario_name': 2, 'cores': 1, 'seed_offset': 0, 'logger': <simulation.simlogger.SimLogger object at 0x7e5fd37d7a10>}

{'patient_inter': 4, 'number_of_nurses': 7}
Scenario parameters: {'_initialising': False, 'patient_inter': 4, 'mean_n_consult_time': 10, 'number_of_nurses': 7, 'warm_up_period': 2000, 'data_collection_period': 6000, 'number_of_runs': 3, 'scenario_name': 3, 'cores': 1, 'seed_offset': 0, 'logger': <simulation.simlogger.SimLogger object at 0x7e5fd37d7a10>}

,run_number,scenario,arrivals,mean_q_time_nurse,mean_time_with_nurse,mean_nurse_utilisation,mean_nurse_utilisation_tw,mean_nurse_q_length,count_nurse_unseen,mean_q_time_nurse_unseen,mean_time_in_system,mean_n_in_system,patient_inter,number_of_nurses
0,0,0,2004,0.486680,9.925934,0.553955,0.553955,0.162551,0,NaN,10.389561,3.486281,3,6
1,1,0,1993,0.746175,10.377197,0.573874,0.573874,0.247854,0,NaN,11.116718,3.691098,3,6
2,2,0,2017,0.386324,9.856724,0.553419,0.553419,0.129869,0,NaN,10.238676,3.450385,3,6
0,0,1,2004,0.121476,9.925934,0.474819,0.474819,0.040573,0,NaN,10.023261,3.364303,3,7
1,1,1,1993,0.226682,10.377197,0.491892,0.491892,0.075296,0,NaN,10.596442,3.518540,3,7

## Run time

In [10]:
# Get run time in seconds
end_time = time.time()
runtime = round(end_time - start_time)

# Display converted to minutes and seconds
print(f"Notebook run time: {runtime // 60}m {runtime % 60}s")

Notebook run time: 0m 0s